ConferenceInfrastructure/Controllers/ConferencesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ConferenceDomain.Model;
using ConferenceInfrastructure;

namespace ConferenceInfrastructure.Controllers
{
    public class ConferencesController : Controller
    {
        private readonly DbconferenceContext _context;

        public ConferencesController(DbconferenceContext context)
        {
            _context = context;
        }

        // GET: Conferences
        public async Task<IActionResult> Index()
        {
            var dbconferenceContext = _context.Conferences.Include(c => c.Organizer).Include(c => c.Topic);
            return View(await dbconferenceContext.ToListAsync());
        }

        // GET: Conferences/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var conference = await _context.Conferences
                .Include(c => c.Organizer)
                .Include(c => c.Topic)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (conference == null)
            {
                return NotFound();
            }

            return View(conference);
        }

        // GET: Conferences/Create
        public IActionResult Create()
        {
            ViewData["OrganizerId"] = new SelectList(_context.Organizers, "Id", "Login");
            ViewData["TopicId"] = new SelectList(_context.Topics, "Id", "Name");
            return View();
        }

        // POST: Conferences/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,TopicId,Info,Cost,DateTime,Duration,OrganizerId,Id")] Conference conference)
        {
            // Перевірка на унікальність всіх даних конференції
            if (_context.Conferences.Any(c => c.Name == conference.Name && c.DateTime == conference.DateTime && c.OrganizerId == conference.OrganizerId))
            {
                ModelState.AddModelError("", "Конференція з такою назвою, датою та організатором вже існує");
            }
            if (ModelState.IsValid)
            {
                _context.Add(conference);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["OrganizerId"] = new SelectList(_context.Organizers, "Id", "Login", conference.OrganizerId);
            ViewData["TopicId"] = new SelectList(_context.Topics, "Id", "Name", conference.TopicId);
            return View(conference);
        }

        // GET: Conferences/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var conference = await _context.Conferences.FindAsync(id);
            if (conference == null)
            {
                return NotFound();
            }
            ViewData["OrganizerId"] = new SelectList(_context.Organizers, "Id", "Login", conference.OrganizerId);
            ViewData["TopicId"] = new SelectList(_context.Topics, "Id", "Name", conference.TopicId);
            return View(conference);
        }

        // POST: Conferences/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Name,TopicId,Info,Cost,DateTime,Duration,OrganizerId,Id")] Conference conference)
        {
            if (id != conference.Id)
            {
                return NotFound();
            }

            // Перевірка на унікальність назви, дати та організатора конференції, ігноруючи поточну конференцію
            if (_context.Conferences.Any(c => c.Id != id && c.Name == conference.Name && c.DateTime == conference.DateTime && c.OrganizerId == conference.OrganizerId))
            {
                ModelState.AddModelError("", "Конференція з такою назвою, датою та організатором вже існує");
            }
            // Форматування ціни без десяткових знаків
            if (conference.Cost.HasValue)
            {
                conference.Cost = Math.Round(conference.Cost.Value, 0);
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(conference);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ConferenceExists(conference.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["OrganizerId"] = new SelectList(_context.Organizers, "Id", "Login", conference.OrganizerId);
            ViewData["TopicId"] = new SelectList(_context.Topics, "Id", "Name", conference.TopicId);
            return View(conference);
        }

        // GET: Conferences/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var conference = await _context.Conferences
                .Include(c => c.Organizer)
                .Include(c => c.Topic)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (conference == null)
            {
                return NotFound();
            }

            return View(conference);
        }

        // POST: Conferences/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var conference = await _context.Conferences.FindAsync(id);
            if (conference != null)
            {
                // Видалення всіх пов'язаних записів SignUp
                var signUps = _context.SignUps.Where(s => s.ConferenceId == id);
                _context.SignUps.RemoveRange(signUps);

                _context.Conferences.Remove(conference);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> SignUpForConference(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            // Завантаження конференції разом з організатором
            var conference = await _context.Conferences
                .Include(c => c.Organizer) // Додавання цього рядка
                .FirstOrDefaultAsync(c => c.Id == id);

            if (conference == null || conference.Organizer == null)
            {
                return NotFound();
            }

            return RedirectToAction("Create", "SignUps", new { conferenceId = conference.Id, conferenceName = conference.Name, conferenceDateTime = conference.DateTime, organizerName = conference.Organizer.Name });
        }



        private bool ConferenceExists(int id)
        {
            return _context.Conferences.Any(e => e.Id == id);
        }
    }
}

ConferenceInfrastructure/Views/Conferences/Create.cshtml
@model ConferenceDomain.Model.Conference

@{
    ViewData["Title"] = "Створити";
}

<h1>Створення</h1>

<h4>Конференція</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TopicId" class="control-label"></label>
                <select asp-for="TopicId" class ="form-control" asp-items="ViewBag.TopicId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Info" class="control-label"></label>
                <input asp-for="Info" class="form-control" />
                <span asp-validation-for="Info" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cost" class="control-label"></label>
                <input asp-for="Cost" class="form-control" />
                <span asp-validation-for="Cost" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateTime" class="control-label"></label>
                <input asp-for="DateTime" class="form-control" />
                <span asp-validation-for="DateTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Duration" class="control-label"></label>
                <input asp-for="Duration" class="form-control" />
                <span asp-validation-for="Duration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Organizer" class="control-label"></label>
                <select asp-for="OrganizerId" class ="form-control" asp-items="ViewBag.OrganizerId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Створити" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Повернутись до списку</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ConferenceInfrastructure/Views/Conferences/Delete.cshtml
@model ConferenceDomain.Model.Conference

@{
    ViewData["Title"] = "Delete";
}

<h1>Видалення</h1>

<h3>Ви впевнені, що хочете видалити дану конференцію?</h3>
<div>
    <h4>Конференція</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Info)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Info)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cost)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cost)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Duration)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Duration)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Organizer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Organizer.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Topic)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Topic.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Видалити" class="btn btn-danger" /> |
        <a asp-action="Index">Повернутись до списку</a>
    </form>
</div>

ConferenceInfrastructure/Views/Conferences/Details.cshtml
@model ConferenceDomain.Model.Conference

@{
    ViewData["Title"] = "Деталі";
}

<h1>Деталі</h1>

<div>
    <h4>Конференція</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Info)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Info)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cost)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cost)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Duration)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Duration)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Organizer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Organizer.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Topic)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Topic.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Змінити</a> |
    <a asp-action="Index">Повернутись до списку</a>
</div>

ConferenceInfrastructure/Views/Conferences/Edit.cshtml
@model ConferenceDomain.Model.Conference

@{
    ViewData["Title"] = "Edit";
}

<h1>Редагування</h1>

<h4>Конференція</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TopicId" class="control-label"></label>
                <select asp-for="TopicId" class="form-control" asp-items="ViewBag.TopicId"></select>
                <span asp-validation-for="TopicId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Info" class="control-label"></label>
                <input asp-for="Info" class="form-control" />
                <span asp-validation-for="Info" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cost" class="control-label"></label>
                <input asp-for="Cost" class="form-control" />
                <span asp-validation-for="Cost" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateTime" class="control-label"></label>
                <input asp-for="DateTime" class="form-control" />
                <span asp-validation-for="DateTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Duration" class="control-label"></label>
                <input asp-for="Duration" class="form-control" />
                <span asp-validation-for="Duration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrganizerId" class="control-label"></label>
                <select asp-for="OrganizerId" class="form-control" asp-items="ViewBag.OrganizerId"></select>
                <span asp-validation-for="OrganizerId" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="submit" value="Зберегти" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Повернутись до списку</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ConferenceInfrastructure/Views/Conferences/Index.cshtml
@model IEnumerable<ConferenceDomain.Model.Conference>

@{
    ViewData["Title"] = "Index";
}

<h1>Конференції</h1>

<p>
    <a asp-action="Create">Створити нову конференцію</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                <h1>        </h1>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Topic)
            </th>
            <!-- <th>
                @Html.DisplayNameFor(model => model.Info)
            </th>-->
            <th>
                @Html.DisplayNameFor(model => model.Cost)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Duration)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Organizer)
            </th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
       
        <tr>
            <td>
                <a asp-controller="Conferences" asp-action="SignUpForConference" asp-route-id="@item.Id">Зареєструватись</a>
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Topic.Name)
            </td>
                <!--  <td>
                @Html.DisplayFor(modelItem => item.Info)
                </td>-->
            <td>
                @Html.DisplayFor(modelItem => item.Cost)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Duration)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Organizer.Name)
            </td>
            
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Редагувати</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Деталі</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Видалити</a>
            </td>
        </tr>
}
    </tbody>
</table>

<div class="row">
    <div class="col-3">
        <div id="countByTopicChart"></div>
    </div>
</div>

@section Scripts
{
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
        google.charts.load('current', { 'packages': ['corechart'] });
        google.charts.setOnLoadCallback(drawCharts);

        function drawCharts() {
            fetch('/api/chart/countByTopic')
                .then(response => response.json())
                .then(data => {
                    const dataTable = new google.visualization.DataTable();
                    dataTable.addColumn('string', 'Тема конференцій');
                    dataTable.addColumn('number', 'Кількість конференцій');

                    data.forEach(item => {
                        dataTable.addRow([item.topic, item.count]);
                    });

                    const options = {
                        title: 'Конференції за темами',
                        width: 600,
                        height: 400,
                        legend: { position: 'none' },
                    };

                    const chart = new google.visualization.ColumnChart(document.getElementById('countByTopicChart'));

                    chart.draw(dataTable, options);
                });
        }
    </script>
}